# Generated by Django 3.1.6 on 2021-10-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updating',
            name='title1',
            field=models.TextField(default='emir', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updating',
            name='middleDescription',
            field=models.TextField(max_length=240),
        ),
        migrations.AlterField(
            model_name='updating',
            name='middleTitle',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='updating',
            name='title',
            field=models.TextField(default='Updating'),
        ),
        migrations.AlterField(
            model_name='updating',
            name='titleDescription',
            field=models.TextField(max_length=120),
        ),
    ]
