# Generated by Django 3.1.6 on 2021-10-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211008_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FooterTitle', models.CharField(max_length=40)),
                ('FooterContent', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeadTitle', models.CharField(max_length=40)),
                ('HeadContent', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='OfferFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferFiveTitle', models.CharField(max_length=40)),
                ('OfferFiveContent', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='OfferFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferFourTitle', models.CharField(max_length=40)),
                ('OfferFourContent', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='OfferOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferOneTitle', models.CharField(max_length=40)),
                ('OfferOneContent', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='OfferThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferThreeTitle', models.CharField(max_length=40)),
                ('OfferThreeContent', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='OfferTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferTwoTitle', models.CharField(max_length=40)),
                ('OfferTwoContent', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PansionNeretva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(max_length=40)),
                ('Link1', models.CharField(max_length=40)),
                ('Content1', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='QuadAdvantures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title2', models.CharField(max_length=40)),
                ('Link2', models.CharField(max_length=40)),
                ('Content2', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RaftingAdrenaline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title3', models.CharField(max_length=40)),
                ('Link3', models.CharField(max_length=40)),
                ('Content3', models.TextField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Updating',
        ),
    ]
