# Generated by Django 3.1.6 on 2021-10-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211013_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertwo',
            name='Content1',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
