# Generated by Django 3.1.6 on 2021-10-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211013_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerone',
            name='Content1',
            field=models.CharField(max_length=40),
        ),
    ]
