# Generated by Django 3.1.6 on 2021-10-13 02:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211013_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerfive',
            old_name='Content',
            new_name='Content1',
        ),
        migrations.RenameField(
            model_name='offerfour',
            old_name='Content',
            new_name='Content1',
        ),
        migrations.RemoveField(
            model_name='offerthree',
            name='Content',
        ),
        migrations.AddField(
            model_name='offerfive',
            name='Content2',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerfive',
            name='Content3',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 57, 45, 735654, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfive',
            name='Content4',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 57, 53, 796288, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfive',
            name='Content5',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 57, 57, 769319, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfive',
            name='Content6',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 57, 59, 724065, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfive',
            name='Content7',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 1, 915988, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfive',
            name='Content8',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 3, 371990, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfour',
            name='Content2',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerfour',
            name='Content3',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 5, 914056, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfour',
            name='Content4',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 7, 813292, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfour',
            name='Content5',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 9, 323701, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfour',
            name='Content6',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 13, 266678, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfour',
            name='Content7',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 14, 713187, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfour',
            name='Content8',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 18, 960967, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerthree',
            name='Content1',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerthree',
            name='Content2',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerthree',
            name='Content3',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 20, 300886, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerthree',
            name='Content4',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 21, 761877, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerthree',
            name='Content5',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 23, 146766, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerthree',
            name='Content6',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 24, 393042, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerthree',
            name='Content7',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 26, 73962, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerthree',
            name='Content8',
            field=models.TextField(default=datetime.datetime(2021, 10, 13, 2, 58, 27, 988339, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
