# Generated by Django 3.1.6 on 2021-10-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20211015_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaftingGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rafting', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
