# Generated by Django 3.1.6 on 2021-10-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_raftinggallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raftinggallery',
            name='rafting',
            field=models.ImageField(blank=True, null=True, upload_to='slike/'),
        ),
    ]
