from django.db import models
from django.contrib.auth.models import UserManager

# Create your models here.

class MainContent(models.Model):
    Title = models.CharField(max_length=40)
    TitleSmall = models.CharField(max_length=40, default= None)
    Content = models.TextField(max_length=120)


class PansionNeretva(models.Model):
    Title = models.CharField(max_length=40)
    Link = models.CharField(max_length=40)
    Content = models.TextField(max_length=400)
    


class QuadAdvantures(models.Model):
    Title = models.CharField(max_length=40)
    Link = models.CharField(max_length=40)
    Content = models.TextField(max_length=400)
    objects = UserManager()
class RaftingAdrenaline(models.Model):
    Title = models.CharField(max_length=40)
    Link = models.CharField(max_length=40)
    Content = models.TextField(max_length=400)
    objects = UserManager()
class MiddleSection(models.Model):
    Title = models.CharField(max_length=40)
    Content = models.TextField(max_length=400)
    objects = UserManager()
class OfferOne(models.Model):
    Title = models.CharField(max_length=40)
    Price = models.CharField(max_length=10)
    Content1 = models.TextField(max_length=100)
    Content2 = models.TextField(max_length=100)
    Content3 = models.TextField(max_length=100)
    Content4 = models.TextField(max_length=100)
    Content5 = models.TextField(max_length=100)
    Content6 = models.TextField(max_length=100)
    Content7 = models.TextField(max_length=100)
    Content8 = models.TextField(max_length=100)
    objects = UserManager()

class OfferTwo(models.Model):
    Title = models.CharField(max_length=40)
    Price = models.CharField(max_length=10)
    Content1 = models.TextField(max_length=100, default= None)
    Content2 = models.TextField(max_length=100, default= None)
    Content3 = models.TextField(max_length=100)
    Content4 = models.TextField(max_length=100)
    Content5 = models.TextField(max_length=100)
    Content6 = models.TextField(max_length=100)
    Content7 = models.TextField(max_length=100)
    Content8 = models.TextField(max_length=100)
    objects = UserManager()
class OfferThree(models.Model):
    Title = models.CharField(max_length=40)
    Price = models.CharField(max_length=10)
    Content1 = models.TextField(max_length=100, default= None)
    Content2 = models.TextField(max_length=100, default= None)
    Content3 = models.TextField(max_length=100)
    Content4 = models.TextField(max_length=100)
    Content5 = models.TextField(max_length=100)
    Content6 = models.TextField(max_length=100)
    Content7 = models.TextField(max_length=100)
    Content8 = models.TextField(max_length=100)
    objects = UserManager()
class OfferFour(models.Model):
    Title = models.CharField(max_length=40,)
    Price = models.CharField(max_length=10)
    Content1 = models.TextField(max_length=100, default= None)
    Content2 = models.TextField(max_length=100, default= None)
    Content3 = models.TextField(max_length=100)
    Content4 = models.TextField(max_length=100)
    Content5 = models.TextField(max_length=100)
    Content6 = models.TextField(max_length=100)
    Content7 = models.TextField(max_length=100)
    Content8 = models.TextField(max_length=100)
    objects = UserManager()
class OfferFive(models.Model):
    Title = models.CharField(max_length=40)
    Price = models.CharField(max_length=10)
    Content1 = models.TextField(max_length=100, default= None)
    Content2 = models.TextField(max_length=100, default= None)
    Content3 = models.TextField(max_length=100)
    Content4 = models.TextField(max_length=100)
    Content5 = models.TextField(max_length=100)
    Content6 = models.TextField(max_length=100)
    Content7 = models.TextField(max_length=100)
    Content8 = models.TextField(max_length=100)
    objects = UserManager()
class Footer(models.Model):
    Title = models.CharField(max_length=40)
    Content = models.TextField(max_length=150)
    objects = UserManager()

class PhoneNumber(models.Model):
    number = models.CharField(max_length=15)

class RaftingGallery(models.Model):
    rafting1 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting2= models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting3 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting4 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting5 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting6 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting7 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting8 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting9 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting10 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting11 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting12 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting13 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting14 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting15 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting16 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting17 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting18 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
    rafting19 = models.ImageField(null=True, blank=True,upload_to= "rafting/")
class PansionGallery(models.Model):
    Pansion1 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion2= models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion3 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion4 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion5 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion6 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion7 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion8 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion9 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion10 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion11 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion12 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion13 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion14 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion15 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion16 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion17 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion18 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
    Pansion19 = models.ImageField(null=True, blank=True,upload_to= "Pansion/")
class QuadGallery(models.Model):
    Quad1 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad2= models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad3 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad4 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad5 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad6 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad7 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad8 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad9 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad10 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad11 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad12 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad13 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad14 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad15 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad16 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad17 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad18 = models.ImageField(null=True, blank=True,upload_to= "Quad/")
    Quad19 = models.ImageField(null=True, blank=True,upload_to= "Quad/")